parameters:
  cl_slack.http_client.class: GuzzleHttp\Client
  cl_slack.api_client.class: CL\Slack\Transport\ApiClient

services:
  cl_slack.http_client:
    class: %cl_slack.http_client.class%

  cl_slack.api_client:
    class: %cl_slack.api_client.class%
    arguments:
      - %cl_slack.api_token%
      - @jms_serializer.serializer
