parameters:
  cl_slack.api_client.class: GuzzleHttp\Client
  cl_slack.api_method_factory.class: CL\Slack\Api\Method\MethodFactory
  cl_slack.api_method_helper.class: CL\Slack\Api\Method\MethodHelper
  cl_slack.api_method_transport.class: CL\Slack\Api\Method\Transport\Transport
  cl_slack.outgoing_webhook.request_factory.class: CL\Slack\OutgoingWebhook\Request\OutgoingWebhookRequestFactory

services:
  cl_slack.api_client:
    class: %cl_slack.api_client.class%
  cl_slack.api_method_factory:
    class: %cl_slack.api_method_factory.class%
  cl_slack.api_method_helper:
    class: %cl_slack.api_method_helper.class%
    arguments: [@cl_slack.api_method_factory, @cl_slack.api_method_transport, %cl_slack.api_token%]
  cl_slack.api_method_transport:
    class: %cl_slack.api_method_transport.class%
    arguments: [@cl_slack.api_client]
  cl_slack.outgoing_webhook.request_factory:
    class: %cl_slack.outgoing_webhook.request_factory.class%
    arguments: [[]]
