parameters:
    cl_slack.payload.transport.class: CL\Bundle\SlackBundle\Slack\Payload\Transport

services:
    cl_slack.payload.transport:
        class: %cl_slack.payload.transport.class%
        arguments: [%cl_slack.username%, %cl_slack.token%]
