parameters:
  cl_slack.api_client.class: CL\Slack\Transport\ApiClient
  cl_slack.payload_registry.class: CL\Slack\Util\PayloadRegistry
  cl_slack.payload_serializer.class: CL\Slack\Util\PayloadSerializer

services:
  cl_slack.api_client:
    class: %cl_slack.api_client.class%
    arguments:
      - %cl_slack.api_token%
      - @cl_slack.payload_serializer

  cl_slack.payload_registry:
    class: %cl_slack.payload_registry.class%

  cl_slack.payload_serializer:
    class: %cl_slack.payload_serializer.class%
    arguments:
      - @jms_serializer.serializer
