parameters:
    cl_slack.webhook.transport.class: CL\Bundle\SlackBundle\Slack\Webhook\Transport

services:
    cl_slack.webhook.transport:
        class: %cl_slack.webhook.transport.class%
        arguments: [%cl_slack.webhook_url%]
