parameters:
  cl_slack.api_method_transport.class: CL\Bundle\SlackBundle\Slack\Api\Method\Transport\Transport
  cl_slack.api_method_factory.class: CL\Bundle\SlackBundle\Slack\Api\Method\ApiMethodFactory
  cl_slack.api_method.search_all.class: CL\Bundle\SlackBundle\Slack\Api\Method\SearchAllApiMethod
  cl_slack.api_method.search_files.class: CL\Bundle\SlackBundle\Slack\Api\Method\SearchFilesApiMethod
  cl_slack.api_method.search_messages.class: CL\Bundle\SlackBundle\Slack\Api\Method\SearchMessagesApiMethod
  cl_slack.api_method.auth_test.class: CL\Bundle\SlackBundle\Slack\Api\Method\AuthTestApiMethod

services:
  cl_slack.api_method_transport:
    class: %cl_slack.api_method_transport.class%
    arguments: [%cl_slack.api_base_url%]
  cl_slack.api_method_factory:
    class: %cl_slack.api_method_factory.class%
  cl_slack.api_method.search_all:
    class: %cl_slack.api_method.search_all.class%
    tags:
      - { name: cl_slack.api_method, alias: search.all }
  cl_slack.api_method.search_files:
    class: %cl_slack.api_method.search_files.class%
    tags:
      - { name: cl_slack.api_method, alias: search.files }
  cl_slack.api_method.search_messages:
    class: %cl_slack.api_method.search_messages.class%
    tags:
      - { name: cl_slack.api_method, alias: search.messages }
  cl_slack.api_method.auth_test:
    class: %cl_slack.api_method.auth_test.class%
    tags:
      - { name: cl_slack.api_method, alias: auth.test }
