tools:
  php_code_sniffer:
    config:
      standard: PSR2
  php_cpd: true
  php_cs_fixer:
    config:
      level: all
  php_hhvm: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer:
    excluded_paths:
      - 'Tests/*'
  sensiolabs_security_checker: true
